[package]
name = "gnostr"
version = "0.0.1"
authors = ["gnostr <admin@gnostr.org>", "Richard Tjerngren <rtjerngren@spotify.com>"]
edition = "2018"

[dependencies]
gnostr_lib = { path = "../lib" }
clap = "2"
